default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: tauhid        # Use your PostgreSQL username here
  password: 1220          # Password you just set
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: music_app_development

test:
  <<: *default
  database: book_store_test

production:
  <<: *default
  database: book_store_production
  username: tauhid
  password: <%= ENV['BOOK_STORE_DATABASE_PASSWORD'] %>
